import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const api=fs.readFileSync(new URL('../api/reshape.js',import.meta.url),'utf8');
assert.match(html,/rejectedCandidateModal/);
assert.match(html,/View rejected candidate/);
assert.match(html,/friendlyRejectionReason/);
assert.match(html,/zoom\\s\+\(\?:in\|into\)|zoom\\s\+\(\?:in\|into\)/);
assert.match(html,/subjectCropMode='headshot'/);
assert.match(html,/\.38/);
assert.match(html,/\{\.\.\.priorPlanForModify, \.\.\.\(j\.bannerPlan/);
assert.doesNotMatch(html,/\{\.\.\.\(j\.bannerPlan\|\|baseData\.bannerPlan\|\|\{\}\), \.\.\.priorPlanForModify\}/);
assert.match(api,/CROP_SUBJECTS_HEADSHOT/);
assert.match(api,/subjectCropMode="headshot"/);
assert.match(api,/rejectedCandidate:candidate/);
assert.match(api,/Candidate modification rejected by visual QA/);
assert.match(api,/responsePlan=\{\.\.\.priorPlan,\.\.\.universalPlan\}/);
console.log('PASS v8.11 headshot/rejected-candidate tests');
